[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.extract-leads-background]
    runtime = "js"
    background = true

[dev]
  functions = "netlify/functions"
  functionsPort = 9999
  timeout = 60

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
